package controller;

enum RequestType {
		CONNECT_USER,
		CONNECT_ADMIN,
		PASSWORD_FORGOTTEN,
		DISCONNECT,
		REGISTER,
		GET_PROFILE_INFORMATIONS,
		MODIFY_PROFILE,
		REMOVE_PROFILE,
		SEARCH_RIDE,
		ADD_WORKPLACE,
		GET_LIST_WORKPLACE,
		DELETE_WORKPLACE,
		ADD_TOWN,
		GET_LIST_TOWN,
		DELETE_TOWN,
	}
